### PR TITLE
[General] Initial update to Swift 3.0

### PR DESCRIPTION
**Pull request by sunshinejr**
Hey @delba 🐼 

I was playing with Swift 3.0 project and wanted to use JASON as a mapper, so I've made few changes so it works with Swift 3.0 :)

### CODE REVIEW

**Comment by delba** [comment]
Awesome! I'm gonna create a swift-3.0 branch and merge it tomorrow. Thank you Luke :)

**Comment by sunshinejr** [comment]
Awesome! 🎉

**Comment by delba** [comment]
Could you please create a new PR on the `swift-3.0` branch ? I'll merge it right away.

Thanks!

**Comment by sunshinejr** [comment]
Done!

**Pull request closed without merging**
