### PR TITLE
Update targets to build with Swift 4

### PR DESCRIPTION
**Pull request by eseay**
- Update project settings to match Xcode 9 suggestions
- Update Float initializer to use new "exactly" name for NSNumber parameters

### CODE REVIEW

**Comment by eseay** [comment]
I forgot to update the travis config, but it appears that travis does not yet support Xcode 9. These changes to add Swift 4 support are minimal, so hopefully once the travis platform is up to date, this will work.

**Comment by eseay** [comment]
Looks like Travis has not yet updated to Xcode 9. Will hopefully be able to rebuild successfully when that time comes.

**Comment by aymericio** [comment]
@eseay you can rebuild your last commit. Travis supports now [Xcode 9](https://docs.travis-ci.com/user/reference/osx/#Xcode-90).

**Comment by delba** [comment]
Hi @eseay, thank you very much for the PR, `JASON` has been updated to the latest Swift version.
Thanks again :)

**Pull request closed without merging**
